name: Laravel Deployment

on:
  push:
    branches:
      - development
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/yevhen16_vps_usr/data/www/yevhen16.vps-dns.info
            git fetch --prune
            git pull origin development

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            npm install
            npm run build

            php artisan optimize:clear

            sudo chown -R yevhen16_vps_usr:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            sudo service php8.3-fpm reload